```
###############################
##                           ##
##  Deep Learning in Python  ##
##                           ##
###############################

§2 Introduction to TensorFlow in Python

§2.1 Introduction to TensorFlow

§2.1.2 Basic operations
```

**1. What is a TensorFlow operation?**

![What is a TensorFlow operation](ref4.%20What%20is%20a%20TensorFlow%20operation.jpg)

**2. Code of applying the addition operator:**

**3. Code of defining tensors in TensorFlow:**

In [1]:
import tensorflow as tf

# 0D Tensor
d0 = tf.ones((1, ))
d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [2]:
# 1D Tensor
d1 = tf.ones((2, ))
d1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [3]:
# 2D Tensor
d2 = tf.ones((2, 2))
d2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [4]:
# 3D Tensor
d3 = tf.ones((2, 2, 2))
d3

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [5]:
# Print the 3D tensor
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


**4. How to define constants in TensorFlow?**

* A constant is the simplest category of tensor:

    * cannot be changed and not trainable
    
    * can have any dimension

**5. Code of defining constants in TensorFlow:**

In [6]:
from tensorflow import constant

# Define a 2x3 constant.
a = constant(3, shape=[2, 3])
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [7]:
# Define a 2x2 constant.
b = constant([1, 2, 3, 4], shape=[2, 2])
b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

**6 How to use convenience functions to define constants?**

![Using convenience functions to define constants](ref2.%20Using%20convenience%20functions%20to%20define%20constants.jpg)

**7. Code of defining and initializing variables:**

In [8]:
import tensorflow as tf

# Define a variable
a0 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.float32)
a1 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.int16)
a0, a1

(<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(6,) dtype=int16, numpy=array([1, 2, 3, 4, 5, 6], dtype=int16)>)

In [9]:
# Define a constant
b = tf.constant(2, tf.float32)
b

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [10]:
# Compute their product
c0 = tf.multiply(a0, b)
c1 = a0 * b
c0, c1

(<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 2.,  4.,  6.,  8., 10., 12.], dtype=float32)>,
 <tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 2.,  4.,  6.,  8., 10., 12.], dtype=float32)>)

**8. Practice exercises for constants and variables:**

$\blacktriangleright$ **Package pre-loading:**

In [13]:
import pandas as pd
import numpy as np

$\blacktriangleright$ **Data pre-loading:**

In [17]:
df = pd.read_csv('ref3. UCI credit card.csv', dtype=np.float64)
credit_numpy = df[['EDUCATION', 'MARRIAGE', 'AGE', 'BILL_AMT1']].to_numpy()

(30000, 4)

$\blacktriangleright$ **Defining data as constants practice:**

In [18]:
# Import constant from TensorFlow
from tensorflow import constant

# Convert the credit_numpy array into a tensorflow constant
credit_constant = constant(credit_numpy)

# Print constant datatype
print('The datatype is:', credit_constant.dtype)

# Print constant shape
print('The shape is:', credit_constant.shape)

The datatype is: <dtype: 'float64'>
The shape is: (30000, 4)


$\blacktriangleright$ **Defining variables practice:**

In [19]:
import tensorflow as tf

# Define the 1-dimensional variable A1
A1 = tf.Variable([1, 2, 3, 4])

# Print the variable A1
print(A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print(B1)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>
[1 2 3 4]
