```
###############################
##                           ##
##  Deep Learning in Python  ##
##                           ##
###############################

§2 Introduction to TensorFlow in Python

§2.1 Introduction to TensorFlow

§2.1.3 Advanced operations
```

**1. What are the advanced operations?**

![Overview of advanced operations](ref5.%20Overview%20of%20advanced%20operations.jpg)

**2. How to find the optimum?**

* In many problems, it is in need to find the optimum of a function:

    * **Minimum**: the lowest value of a loss function

    * **Maximum**: the highest value of the objective function

* It is possible to do this by using the `gradient()` operation:

    * **Optimum**: find a point where $gradient = 0$

    * **Minimum**: change in $gradient > 0$
    
    * **Maximum**: change in $gradient < 0$

**3. How to calculate the gradient?**

![Calculating the gradient](ref6.%20Calculating%20the%20gradient.jpg)

**4. Code of gradients in TensorFlow:**

In [1]:
# Import tensorflow under the alias tf
import tensorflow as tf

# Define x
x = tf.Variable(-1.0)

x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-1.0>

In [2]:
# Define y within instance of GradientTape
with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.multiply(x, x)

y

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [3]:
# Evaluate the gradient of y at x = -1
g = tape.gradient(y, x)
print(g.numpy())

-2.0


**5. How to deal with images as tensors?**

![Images as tensors](ref7.%20Images%20as%20tensors.jpg)

**6. How to reshape a grayscale image?**

![How to reshape a grayscale image](ref8.%20How%20to%20reshape%20a%20grayscale%20image.jpg)

**7. Code of reshaping a grayscale image:**

In [4]:
# Import tensorflow as alias tf
import tensorflow as tf

# Generate grayscale image
gray = tf.random.uniform([2, 2], maxval=255, dtype='int32')

gray

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 42, 254],
       [ 15,  48]], dtype=int32)>

In [5]:
# Reshape grayscale image
gray = tf.reshape(gray, [2 * 2, 1])

gray

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[ 42],
       [254],
       [ 15],
       [ 48]], dtype=int32)>

**8. How to reshape a color image?**

![How to reshape a color image](ref9.%20How%20to%20reshape%20a%20color%20image.jpg)

**9. Code of reshaping a color image:**

In [6]:
# Import tensorflow as alias tf
import tensorflow as tf

# Generate color image
color = tf.random.uniform([2, 2, 3], maxval=255, dtype='int32')

color

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[193, 207,   2],
        [188,  27, 105]],

       [[138, 244,  80],
        [177,  52,  60]]], dtype=int32)>

In [7]:
# Reshape color image
color = tf.reshape(color, [2 * 2, 3])

color

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[193, 207,   2],
       [188,  27, 105],
       [138, 244,  80],
       [177,  52,  60]], dtype=int32)>

**10. Practice exercises for advanced operations:**

$\blacktriangleright$ **Diagram of images for reshaping:**

![Sign language letter A](ref10.%20Sign%20language%20letter%20A.jpg)

$\blacktriangleright$ **Package pre-loading:**

In [8]:
import numpy as np
from tensorflow import reshape

$\blacktriangleright$ **Data pre-loading:**

In [9]:
gray_tensor = np.loadtxt("ref11. Gray tensor.csv", delimiter=',')

color_tensor = np.loadtxt("ref12. Color tensor.csv", delimiter=',')
color_tensor = color_tensor.reshape(color_tensor.shape[0],
                                    color_tensor.shape[1] // 3, 3)

$\blacktriangleright$ **Tensor reshaping practice:**

In [10]:
# Reshape the grayscale image tensor into a vector
gray_vector = reshape(gray_tensor, (-1, 1))

# Reshape the color image tensor into a vector
color_vector = reshape(color_tensor, (-1, 1))

$\blacktriangleright$ **Diagram of gradient descent:**

![Gradient plot](ref13.%20Gradient%20plot.png)

$\blacktriangleright$ **Package re-pre-loading:**

In [11]:
from tensorflow import Variable, GradientTape, multiply

$\blacktriangleright$ **Gradients optimization practice:**

In [12]:
def compute_gradient(x0):
    # Define x as a variable with an initial value of x0
    x = Variable(x0)
    with GradientTape() as tape:
        tape.watch(x)
        # Define y using the multiply operation
        y = multiply(x, x)
    # Return the gradient of y with respect to x
    return tape.gradient(y, x).numpy()


# Compute and print gradients at x = -1, 1, and 0
print(compute_gradient(-1.0))
print(compute_gradient(1.0))
print(compute_gradient(0.0))

-2.0
2.0
0.0


$\blacktriangleright$ **Package re-pre-loading:**

In [13]:
from tensorflow import constant, matmul, reduce_sum

$\blacktriangleright$ **Data re-pre-loading:**

In [14]:
letter = constant([[1., 0., 1.], [1., 1., 0.], [1., 0., 1.]])

model = constant([[1., 0., -1.]])

$\blacktriangleright$ **Image data working practice:**

In [15]:
# Reshape model from a 1x3 to a 3x1 tensor
model = reshape(model, (3, 1))

# Multiply letter by model
output = matmul(letter, model)

# Sum over output and print prediction using the numpy method
prediction = reduce_sum(output)
print(prediction.numpy())

1.0
