<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Input-data" data-toc-modified-id="Input-data-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Input data</a></span><ul class="toc-item"><li><span><a href="#[note-1]-Importing-data-for-use-in-TensorFlow" data-toc-modified-id="[note-1]-Importing-data-for-use-in-TensorFlow-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span><code>[note-1]</code> Importing data for use in TensorFlow</a></span></li><li><span><a href="#[code-1]-How-to-import-and-convert-data" data-toc-modified-id="[code-1]-How-to-import-and-convert-data-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span><code>[code-1]</code> How to import and convert data</a></span></li><li><span><a href="#[note-2]-Parameters-of-read_csv()" data-toc-modified-id="[note-2]-Parameters-of-read_csv()-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span><code>[note-2]</code> Parameters of <code>read_csv()</code></a></span></li><li><span><a href="#[note-3]-Using-mixed-type-datasets" data-toc-modified-id="[note-3]-Using-mixed-type-datasets-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span><code>[note-3]</code> Using mixed type datasets</a></span></li><li><span><a href="#[code-2]-Setting-the-data-type" data-toc-modified-id="[code-2]-Setting-the-data-type-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span><code>[code-2]</code> Setting the data type</a></span></li><li><span><a href="#[task-1]-Load-data-using-pandas" data-toc-modified-id="[task-1]-Load-data-using-pandas-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span><code>[task-1]</code> Load data using pandas</a></span></li><li><span><a href="#[task-2]-Setting-the-data-type" data-toc-modified-id="[task-2]-Setting-the-data-type-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span><code>[task-2]</code> Setting the data type</a></span></li></ul></li><li><span><a href="#Loss-functions" data-toc-modified-id="Loss-functions-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Loss functions</a></span><ul class="toc-item"><li><span><a href="#[note-1]-Introduction-to-loss-functions" data-toc-modified-id="[note-1]-Introduction-to-loss-functions-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span><code>[note-1]</code> Introduction to loss functions</a></span></li><li><span><a href="#[note-2]-Common-loss-functions-in-TensorFlow" data-toc-modified-id="[note-2]-Common-loss-functions-in-TensorFlow-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span><code>[note-2]</code> Common loss functions in TensorFlow</a></span></li><li><span><a href="#[note-3]-Why-is-it-in-need-to-care-about-loss-functions?" data-toc-modified-id="[note-3]-Why-is-it-in-need-to-care-about-loss-functions?-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span><code>[note-3]</code> Why is it in need to care about loss functions?</a></span></li><li><span><a href="#[code-1]-Defining-a-loss-function" data-toc-modified-id="[code-1]-Defining-a-loss-function-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span><code>[code-1]</code> Defining a loss function</a></span></li><li><span><a href="#[task-1]-Loss-functions-in-TensorFlow" data-toc-modified-id="[task-1]-Loss-functions-in-TensorFlow-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span><code>[task-1]</code> Loss functions in TensorFlow</a></span></li><li><span><a href="#[task-2]-Modifying-the-loss-function" data-toc-modified-id="[task-2]-Modifying-the-loss-function-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span><code>[task-2]</code> Modifying the loss function</a></span></li></ul></li><li><span><a href="#Linear-regression" data-toc-modified-id="Linear-regression-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Linear regression</a></span><ul class="toc-item"><li><span><a href="#[note-1]-What-is-linear-regression?" data-toc-modified-id="[note-1]-What-is-linear-regression?-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span><code>[note-1]</code> What is linear regression?</a></span></li><li><span><a href="#[note-2]-The-linear-regression-model" data-toc-modified-id="[note-2]-The-linear-regression-model-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span><code>[note-2]</code> The linear regression model</a></span></li><li><span><a href="#[code-1]-Linear-regression-in-TensorFlow" data-toc-modified-id="[code-1]-Linear-regression-in-TensorFlow-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span><code>[code-1]</code> Linear regression in TensorFlow</a></span></li><li><span><a href="#[task-1]-Set-up-a-linear-regression" data-toc-modified-id="[task-1]-Set-up-a-linear-regression-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span><code>[task-1]</code> Set up a linear regression</a></span></li></ul></li><li><span><a href="#Batch-training" data-toc-modified-id="Batch-training-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Batch training</a></span><ul class="toc-item"><li><span><a href="#What-is-batch-training?" data-toc-modified-id="What-is-batch-training?-4.1"><span class="toc-item-num">4.1&nbsp;&nbsp;</span>What is batch training?</a></span></li><li><span><a href="#What-is-the-chunksize-parameter?" data-toc-modified-id="What-is-the-chunksize-parameter?-4.2"><span class="toc-item-num">4.2&nbsp;&nbsp;</span>What is the <code>chunksize</code> parameter?</a></span></li><li><span><a href="#Code-of-the-chunksize-parameter:" data-toc-modified-id="Code-of-the-chunksize-parameter:-4.3"><span class="toc-item-num">4.3&nbsp;&nbsp;</span>Code of the <code>chunksize</code> parameter:</a></span></li><li><span><a href="#Code-of-training-a-linear-model-in-batches:" data-toc-modified-id="Code-of-training-a-linear-model-in-batches:-4.4"><span class="toc-item-num">4.4&nbsp;&nbsp;</span>Code of training a linear model in batches:</a></span></li><li><span><a href="#Compare-full-sample-versus-batch-training,-what-are-the-differences?" data-toc-modified-id="Compare-full-sample-versus-batch-training,-what-are-the-differences?-4.5"><span class="toc-item-num">4.5&nbsp;&nbsp;</span>Compare full sample versus batch training, what are the differences?</a></span></li><li><span><a href="#Practice-exercises-for-batch-training:" data-toc-modified-id="Practice-exercises-for-batch-training:-4.6"><span class="toc-item-num">4.6&nbsp;&nbsp;</span>Practice exercises for batch training:</a></span></li></ul></li></ul></div>

# Input data

## `[note-1]` Importing data for use in TensorFlow

* **Data can be imported using `tensorflow`**:

    * useful for managing complex pipelines

* **Simpler option**:

    * import data using `pandas`
    
    * convert data to `numpy` array
    
    * use in `tensorflow` without modification

* Pandas also has methods for handling data in other formats:

    * e.g. `read_json()` , `read_html()` , `read_excel()`

## `[code-1]` How to import and convert data

In [1]:
# Import numpy and pandas
import numpy as np
import pandas as pd

# Load data from csv
housing = pd.read_csv('../Datasets/1. House sales in King County.csv')

# Convert to numpy array
housing = np.array(housing)

print(housing)

[[7129300520 '20141013T000000' 221900.0 ... -122.257 1340 5650]
 [6414100192 '20141209T000000' 538000.0 ... -122.319 1690 7639]
 [5631500400 '20150225T000000' 180000.0 ... -122.233 2720 8062]
 ...
 [1523300141 '20140623T000000' 402101.0 ... -122.299 1020 2007]
 [291310100 '20150116T000000' 400000.0 ... -122.069 1410 1287]
 [1523300157 '20141015T000000' 325000.0 ... -122.299 1020 1357]]


## `[note-2]` Parameters of `read_csv()`

![Parameters of read_csv](../Figures/1.%20Parameters%20of%20read_csv.jpg)

## `[note-3]` Using mixed type datasets

![Using mixed type datasets](../Figures/2.%20Using%20mixed%20type%20datasets.jpg)

## `[code-2]` Setting the data type

In [2]:
# Load KC dataset
housing = pd.read_csv('../Datasets/1. House sales in King County.csv')

# Convert price column to float32
price = np.array(housing['price'], np.float32)

# Convert waterfront column to Boolean
waterfront = np.array(housing['waterfront'], np.bool)

print(price)
print(waterfront)

[221900. 538000. 180000. ... 402101. 400000. 325000.]
[False False False ... False False False]


In [3]:
import tensorflow as tf

# Load KC dataset
housing = pd.read_csv('../Datasets/1. House sales in King County.csv')

# Convert price column to float32
price = tf.cast(housing['price'], tf.float32)

# Convert waterfront column to Boolean
waterfront = tf.cast(housing['waterfront'], tf.bool)

print(price)
print(waterfront)

tf.Tensor([221900. 538000. 180000. ... 402101. 400000. 325000.], shape=(21613,), dtype=float32)
tf.Tensor([False False False ... False False False], shape=(21613,), dtype=bool)


## `[task-1]` Load data using pandas

$\blacktriangleright$ **Task practice**

In [4]:
# Import pandas under the alias pd
import pandas as pd

# Assign the path to a string variable named data_path
data_path = '../Datasets/1. House sales in King County.csv'

# Load the dataset as a dataframe named housing
housing = pd.read_csv(data_path)

# Print the price column of housing
print(housing['price'])

0        221900.0
1        538000.0
2        180000.0
3        604000.0
4        510000.0
           ...   
21608    360000.0
21609    400000.0
21610    402101.0
21611    400000.0
21612    325000.0
Name: price, Length: 21613, dtype: float64


## `[task-2]` Setting the data type

$\blacktriangleright$ **Task practice**

In [5]:
# Import numpy and tensorflow with their standard aliases
import numpy as np
import tensorflow as tf

# Use a numpy array to define price as a 32-bit float
price = np.array(housing['price'], np.float32)

# Define waterfront as a Boolean using cast
waterfront = tf.cast(housing['waterfront'], tf.bool)

# Print price and waterfront
print(price)
print(waterfront)

[221900. 538000. 180000. ... 402101. 400000. 325000.]
tf.Tensor([False False False ... False False False], shape=(21613,), dtype=bool)


# Loss functions

## `[note-1]` Introduction to loss functions

* **Fundamental `tensorflow` operation**:

    * used to train a model
    
    * the measure of model fit

* **Higher value $\rightarrow$ worse fit**:

    * minimize the loss function

## `[note-2]` Common loss functions in TensorFlow

* **TensorFlow has operations for common loss functions**:

    * mean squared error (MSE)
    
    * mean absolute error (MAE)
    
    * Huber error

* **Loss functions are accessible from `tf.keras.losses`**:

    * `tf.keras.losses.MSE()`
    
    * `tf.keras.losses.MAE()`
    
    * `tf.keras.losses.Huber()`

## `[note-3]` Why is it in need to care about loss functions?

* **MSE**:

    * strongly penalizes outliers
    
    * high (gradient) sensitivity near minimum

* **MAE**:

    * scales linearly with the size of the error
    
    * low sensitivity near minimum

* **Huber**:

    * similar to MSE near minimum
    
    * similar to MAE away from the minimum

![Why is it in need to care about loss functions](../Figures/3.%20Why%20is%20it%20in%20need%20to%20care%20about%20loss%20functions.jpg)

## `[code-1]` Defining a loss function

In [32]:
import pandas as pd
import numpy as np

housing = pd.read_csv('../Datasets/1. House sales in King County.csv')

price_log = np.log(np.array(housing['price'], np.float32))
size_log = np.log(np.array(housing['sqft_lot'], np.float32))
targets = price_log
features = size_log
intercept = 0.1
slope = 0.1

predictions = intercept + features * slope

# Import TensorFlow under standard alias
import tensorflow as tf

# Compute the MSE loss
loss = tf.keras.losses.mse(targets, predictions)

loss

<tf.Tensor: shape=(), dtype=float32, numpy=145.44653>

In [33]:
# Define a linear regression model
def linear_regression(intercept, slope=slope, features=features):
    return intercept + features * slope

In [34]:
# Define a loss function to compute the MSE
def loss_function(intercept, slope, targets=targets, features=features):
    # Compute the predictions for a linear model
    predictions = linear_regression(intercept, slope, features)

    # Return the loss
    return tf.keras.losses.mse(targets, predictions)

In [35]:
from sklearn.model_selection import train_test_split

train_features, test_features, train_targets, test_targets = train_test_split(
    features, targets, test_size=0.3, random_state=42)

# Compute the loss for test data inputs
loss_function(intercept, slope, test_targets, test_features)

<tf.Tensor: shape=(), dtype=float32, numpy=145.57338>

In [36]:
# Compute the loss for default data inputs
loss_function(intercept, slope)

<tf.Tensor: shape=(), dtype=float32, numpy=145.44653>

## `[task-1]` Loss functions in TensorFlow

$\blacktriangleright$ **Package pre-loading**

In [37]:
import pandas as pd
import numpy as np

$\blacktriangleright$ **Data pre-loading**

In [38]:
housing = pd.read_csv('../Datasets/1. House sales in King County.csv')
price = np.array(housing['price'], np.float32)
predictions = np.loadtxt(
    '../Datasets/2. House sales in King County predictions data.csv',
    delimiter=',')

$\blacktriangleright$ **Task practice 1/2**

In [39]:
# Import the keras module from tensorflow
from tensorflow import keras

# Compute the mean squared error (mse)
loss = keras.losses.mse(price, predictions)

# Print the mean squared error (mse)
print(loss.numpy())

141171604777.141


$\blacktriangleright$ **Task practice 2/2**

In [40]:
# Import the keras module from tensorflow
from tensorflow import keras

# Compute the mean absolute error (mae)
loss = keras.losses.mae(price, predictions)

# Print the mean absolute error (mae)
print(loss.numpy())

268827.9930163703


## `[task-2]` Modifying the loss function

$\blacktriangleright$ **Package pre-loading**

In [41]:
from tensorflow import constant, Variable, float32

$\blacktriangleright$ **Data pre-loading**

In [42]:
features = constant([1., 2., 3., 4., 5.], dtype=float32)
targets = constant([2., 4., 6., 8., 10.], dtype=float32)

$\blacktriangleright$ **Task practice**

In [43]:
# Initialize a variable named scalar
scalar = Variable(1.0, float32)


# Define the model
def model(scalar, features=features):
    return scalar * features


# Define a loss function
def loss_function(scalar, features=features, targets=targets):
    # Compute the predicted values
    predictions = model(scalar, features)

    # Return the mean absolute error loss
    return keras.losses.mae(targets, predictions)


# Evaluate the loss function and print the loss
print(loss_function(scalar).numpy())

3.0


# Linear regression

## `[note-1]` What is linear regression?

![What is linear regression](../Figures/4.%20What%20is%20linear%20regression.jpg)

## `[note-2]` The linear regression model

* A linear regression model assumes a linear relationship:

    * $price = intercept + size \times slope + error$

* This is an example of a univariate regression:

    * e.g., there is only one feature: `size`

* Multiple regression models have more than one feature.

    * e.g., there are two features: `size` and `location`

## `[code-1]` Linear regression in TensorFlow

In [44]:
import pandas as pd
import numpy as np
import tensorflow as tf

housing = pd.read_csv('../Datasets/1. House sales in King County.csv')

# Define the targets and features
price = np.log(np.array(housing['price'], np.float32))
size = np.log(np.array(housing['sqft_lot'], np.float32))

# Define the intercept and slope
intercept = tf.Variable(0.1, np.float32)
slope = tf.Variable(0.1, np.float32)

In [45]:
# Define a linear regression model
def linear_regression(intercept, slope, features=size):
    return intercept + features * slope

In [46]:
# Compute the predicted values and loss
def loss_function(intercept, slope, targets=price, features=size):
    predictions = linear_regression(intercept, slope)
    return tf.keras.losses.mse(targets, predictions)

In [47]:
# Define an optimization operation
opt = tf.keras.optimizers.Adam()

In [52]:
# Minimize the loss function and print the loss
for j in range(1000):
    opt.minimize(lambda: loss_function(intercept, slope),
                 var_list=[intercept, slope])
    if j == range(1000)[0]:
        print(loss_function(intercept, slope))
        print("\n…\n")
    elif j == range(1000)[-1]:
        print(loss_function(intercept, slope))

tf.Tensor(1.8807738, shape=(), dtype=float32)

…

tf.Tensor(1.4762464, shape=(), dtype=float32)


In [53]:
# Print the trained parameters
print(intercept.numpy(), slope.numpy())

1.3391368 1.2888577


## `[task-1]` Set up a linear regression

$\blacktriangleright$ **Package pre-loading**

In [24]:
import pandas as pd
import numpy as np
from tensorflow import add, multiply, keras

$\blacktriangleright$ **Data pre-loading**

In [54]:
housing = pd.read_csv('../Datasets/1. House sales in King County.csv')
price_log = np.log(np.array(housing['price'], np.float32))
size_log = np.log(np.array(housing['sqft_lot'], np.float32))

$\blacktriangleright$ **Task practice**

In [55]:
# Define a linear regression model
def linear_regression(intercept, slope, features=size_log):
    return add(intercept, multiply(features, slope))


# Set loss_function() to take the variables as arguments
def loss_function(intercept, slope, features=size_log, targets=price_log):
    # Set the predicted values
    predictions = linear_regression(intercept, slope, features)

    # Return the mean squared error loss
    return keras.losses.mse(targets, predictions)


# Compute the loss for different slope and intercept values
print(loss_function(0.1, 0.1).numpy())
print(loss_function(0.1, 0.5).numpy())

145.44653
71.866


## `[task-2]`

$\blacktriangleright$ **Package pre-loading**

In [ ]:
from tensorflow import Variable
import matplotlib.pyplot as plt

$\blacktriangleright$ **Data pre-loading**

In [ ]:
intercept = Variable(5, dtype=np.float32)
slope = Variable(0.001, dtype=np.float32)

$\blacktriangleright$ **Code pre-loading**

In [ ]:
def plot_results(intercept, slope):
    size_range = np.linspace(6, 14, 100)
    price_pred = [intercept + slope * s for s in size_range]
    plt.scatter(size_log, price_log, color='black')
    plt.plot(size_range, price_pred, linewidth=3.0, color='red')
    plt.xlabel('log(size)')
    plt.ylabel('log(price)')
    plt.title('Scatterplot of data and fitted regression line')
    plt.show()

$\blacktriangleright$ **Linear model training practice**

In [ ]:
# Initialize an adam optimizer
opt = keras.optimizers.Adam(0.5)

for j in range(100):
    # Apply minimize, pass the loss function, and supply the variables
    opt.minimize(lambda: loss_function(intercept, slope),
                 var_list=[intercept, slope])

    # Print every 10th value of the loss
    if j % 10 == 0:
        print(loss_function(intercept, slope).numpy())

# Plot data and regression line
plot_results(intercept, slope)

$\blacktriangleright$ **Data pre-loading**

In [ ]:
bedrooms = np.array(housing['bedrooms'], np.float32)
params = Variable([0.1, 0.05, 0.02], dtype=np.float32)

$\blacktriangleright$ **Code pre-loading**

In [ ]:
def print_results(params):
    return print(
        'loss: {:0.3f}, intercept: {:0.3f}, slope_1: {:0.3f}, slope_2: {:0.3f}'
        .format(
            loss_function(params).numpy(), params[0].numpy(),
            params[1].numpy(), params[2].numpy()))

$\blacktriangleright$ **Multiple linear regression practice**

In [ ]:
# Define the linear regression model
def linear_regression(params, feature1=size_log, feature2=bedrooms):
    return params[0] + feature1 * params[1] + feature2 * params[2]


# Define the loss function
def loss_function(params,
                  targets=price_log,
                  feature1=size_log,
                  feature2=bedrooms):
    # Set the predicted values
    predictions = linear_regression(params, feature1, feature2)

    # Use the mean absolute error loss
    return keras.losses.mae(targets, predictions)


# Define the optimize operation
opt = keras.optimizers.Adam()

# Perform minimization and print trainable variables
for j in range(10):
    opt.minimize(lambda: loss_function(params), var_list=[params])
    print_results(params)

# Batch training

## What is batch training?

![What is batch training](ref7.%20What%20is%20batch%20training.jpg)

## What is the `chunksize` parameter?

* `pandas.read_csv()` allows to load data in batches:
	
    * avoid loading entire dataset
	
    * `chunksize` parameter provides batch size

## Code of the `chunksize` parameter:

In [ ]:
# Import pandas and numpy
import pandas as pd
import numpy as np

# Load data in batches
for batch in pd.read_csv('ref1. King county house sales.csv', chunksize=100):
    # Extract price column
    price = np.array(batch['price'], np.float32)

    # Extract size column
    size = np.array(batch['sqft_living'], np.float32)

## Code of training a linear model in batches:

In [ ]:
# Import tensorflow, pandas, and numpy
import tensorflow as tf
import pandas as pd
import numpy as np

In [ ]:
# Define trainable variables
intercept = tf.Variable(0.1, tf.float32)
slope = tf.Variable(0.1, tf.float32)

In [ ]:
# Define the model
def linear_regression(intercept, slope, features):
    return intercept + features * slope

In [ ]:
# Compute predicted values and return loss function
def loss_function(intercept, slope, targets, features):
    predictions = linear_regression(intercept, slope, features)
    return tf.keras.losses.mse(targets, predictions)

In [ ]:
# Define optimization operation
opt = tf.keras.optimizers.Adam()

In [ ]:
# Load the data in batches from pandas
for batch in pd.read_csv('ref1. King county house sales.csv', chunksize=100):
    # Extract the target and feature columns
    price_batch = np.array(batch['price'], np.float32)
    size_batch = np.array(batch['sqft_lot'], np.float32)

    # Minimize the loss function
    opt.minimize(
        lambda: loss_function(intercept, slope, price_batch, size_batch),
        var_list=[intercept, slope])

In [ ]:
# Print parameter values
print(intercept.numpy(), slope.numpy())

## Compare full sample versus batch training, what are the differences?

* Full Sample
    
    1. One update per epoch
    
    2. Accepts dataset without modification
    
    3. Limited by memory

* Batch Training
    
    1. Multiple updates per epoch
    
    2. Requires the division of dataset
    
    3. No limit on dataset size

## Practice exercises for batch training:

$\blacktriangleright$ **Package pre-loading**

In [ ]:
from tensorflow import Variable, keras, float32

$\blacktriangleright$ **Batch train preparing practice**

In [ ]:
# Define the intercept and slope
intercept = Variable(10.0, float32)
slope = Variable(0.5, float32)


# Define the model
def linear_regression(intercept, slope, features):
    # Define the predicted values
    return intercept + features * slope


# Define the loss function
def loss_function(intercept, slope, targets, features):
    # Define the predicted values
    predictions = linear_regression(intercept, slope, features)

    # Define the MSE loss
    return keras.losses.mse(targets, predictions)

$\blacktriangleright$ **Package pre-loading**

In [ ]:
import pandas as pd
import numpy as np

$\blacktriangleright$ **Linear model batches training practice**

In [ ]:
# Initialize adam optimizer
opt = keras.optimizers.Adam()

# Load data in batches
for batch in pd.read_csv('ref1. King county house sales.csv', chunksize=100):
    size_batch = np.array(batch['sqft_lot'], np.float32)

    # Extract the price values for the current batch
    price_batch = np.array(batch['price'], np.float32)

    # Complete the loss, fill in the variable list, and minimize
    opt.minimize(
        lambda: loss_function(intercept, slope, price_batch, size_batch),
        var_list=[intercept, slope])

# Print trained parameters
print(intercept.numpy(), slope.numpy())