<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Constants-and-variables" data-toc-modified-id="Constants-and-variables-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Constants and variables</a></span><ul class="toc-item"><li><span><a href="#[note-1]-What-is-TensorFlow?" data-toc-modified-id="[note-1]-What-is-TensorFlow?-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span><code>[note-1]</code> What is <a href="https://www.tensorflow.org/api_docs/python/tf" target="_blank">TensorFlow</a>?</a></span></li><li><span><a href="#[note-2]-What-is-a-tensor?" data-toc-modified-id="[note-2]-What-is-a-tensor?-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span><code>[note-2]</code> What is a tensor?</a></span></li><li><span><a href="#[code-1]-Defining-tensors-in-TensorFlow" data-toc-modified-id="[code-1]-Defining-tensors-in-TensorFlow-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span><code>[code-1]</code> Defining tensors in TensorFlow</a></span></li><li><span><a href="#[note-3]-Defining-constants-in-TensorFlow" data-toc-modified-id="[note-3]-Defining-constants-in-TensorFlow-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span><code>[note-3]</code> Defining constants in TensorFlow</a></span></li><li><span><a href="#[code-2]-Defining-constants-in-TensorFlow" data-toc-modified-id="[code-2]-Defining-constants-in-TensorFlow-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span><code>[code-2]</code> Defining constants in TensorFlow</a></span></li><li><span><a href="#[note-4]-Using-convenience-functions-to-define-constants" data-toc-modified-id="[note-4]-Using-convenience-functions-to-define-constants-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span><code>[note-4]</code> Using convenience functions to define constants</a></span></li><li><span><a href="#[code-3]-Defining-and-initializing-variables" data-toc-modified-id="[code-3]-Defining-and-initializing-variables-1.7"><span class="toc-item-num">1.7&nbsp;&nbsp;</span><code>[code-3]</code> Defining and initializing variables</a></span></li><li><span><a href="#[task-1]-Defining-data-as-constants" data-toc-modified-id="[task-1]-Defining-data-as-constants-1.8"><span class="toc-item-num">1.8&nbsp;&nbsp;</span><code>[task-1]</code> Defining data as constants</a></span></li><li><span><a href="#[task-2]-Defining-variables" data-toc-modified-id="[task-2]-Defining-variables-1.9"><span class="toc-item-num">1.9&nbsp;&nbsp;</span><code>[task-2]</code> Defining variables</a></span></li></ul></li><li><span><a href="#Basic-operations" data-toc-modified-id="Basic-operations-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Basic operations</a></span><ul class="toc-item"><li><span><a href="#[note-1]-What-is-a-TensorFlow-operation?" data-toc-modified-id="[note-1]-What-is-a-TensorFlow-operation?-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span><code>[note-1]</code> What is a TensorFlow operation?</a></span></li><li><span><a href="#[code-1]-Applying-the-addition-operator" data-toc-modified-id="[code-1]-Applying-the-addition-operator-2.2"><span class="toc-item-num">2.2&nbsp;&nbsp;</span><code>[code-1]</code> Applying the addition operator</a></span></li><li><span><a href="#[note-2]-Performing-tensor-addition" data-toc-modified-id="[note-2]-Performing-tensor-addition-2.3"><span class="toc-item-num">2.3&nbsp;&nbsp;</span><code>[note-2]</code> Performing tensor addition</a></span></li><li><span><a href="#[note-3]-How-to-perform-multiplication-in-TensorFlow" data-toc-modified-id="[note-3]-How-to-perform-multiplication-in-TensorFlow-2.4"><span class="toc-item-num">2.4&nbsp;&nbsp;</span><code>[note-3]</code> How to perform multiplication in TensorFlow</a></span></li><li><span><a href="#[code-2]-Applying-the-multiplication-operators" data-toc-modified-id="[code-2]-Applying-the-multiplication-operators-2.5"><span class="toc-item-num">2.5&nbsp;&nbsp;</span><code>[code-2]</code> Applying the multiplication operators</a></span></li><li><span><a href="#[note-4]-Summing-over-tensor-dimensions" data-toc-modified-id="[note-4]-Summing-over-tensor-dimensions-2.6"><span class="toc-item-num">2.6&nbsp;&nbsp;</span><code>[note-4]</code> Summing over tensor dimensions</a></span></li><li><span><a href="#[code-3]-Summing-over-tensor-dimensions" data-toc-modified-id="[code-3]-Summing-over-tensor-dimensions-2.7"><span class="toc-item-num">2.7&nbsp;&nbsp;</span><code>[code-3]</code> Summing over tensor dimensions</a></span></li><li><span><a href="#[task-1]-Performing-element-wise-multiplication" data-toc-modified-id="[task-1]-Performing-element-wise-multiplication-2.8"><span class="toc-item-num">2.8&nbsp;&nbsp;</span><code>[task-1]</code> Performing element-wise multiplication</a></span></li><li><span><a href="#[task-2]-Making-predictions-with-matrix-multiplication" data-toc-modified-id="[task-2]-Making-predictions-with-matrix-multiplication-2.9"><span class="toc-item-num">2.9&nbsp;&nbsp;</span><code>[task-2]</code> Making predictions with matrix multiplication</a></span></li><li><span><a href="#Practice-question-for-summing-over-tensor-dimensions:" data-toc-modified-id="Practice-question-for-summing-over-tensor-dimensions:-2.10"><span class="toc-item-num">2.10&nbsp;&nbsp;</span>Practice question for summing over tensor dimensions:</a></span></li></ul></li><li><span><a href="#Advanced-operations" data-toc-modified-id="Advanced-operations-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Advanced operations</a></span><ul class="toc-item"><li><span><a href="#What-are-the-advanced-operations?" data-toc-modified-id="What-are-the-advanced-operations?-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>What are the advanced operations?</a></span></li><li><span><a href="#How-to-find-the-optimum?" data-toc-modified-id="How-to-find-the-optimum?-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>How to find the optimum?</a></span></li><li><span><a href="#How-to-calculate-the-gradient?" data-toc-modified-id="How-to-calculate-the-gradient?-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>How to calculate the gradient?</a></span></li><li><span><a href="#Code-of-gradients-in-TensorFlow:" data-toc-modified-id="Code-of-gradients-in-TensorFlow:-3.4"><span class="toc-item-num">3.4&nbsp;&nbsp;</span>Code of gradients in TensorFlow:</a></span></li><li><span><a href="#How-to-deal-with-images-as-tensors?" data-toc-modified-id="How-to-deal-with-images-as-tensors?-3.5"><span class="toc-item-num">3.5&nbsp;&nbsp;</span>How to deal with images as tensors?</a></span></li><li><span><a href="#How-to-reshape-a-grayscale-image?" data-toc-modified-id="How-to-reshape-a-grayscale-image?-3.6"><span class="toc-item-num">3.6&nbsp;&nbsp;</span>How to reshape a grayscale image?</a></span></li><li><span><a href="#Code-of-reshaping-a-grayscale-image:" data-toc-modified-id="Code-of-reshaping-a-grayscale-image:-3.7"><span class="toc-item-num">3.7&nbsp;&nbsp;</span>Code of reshaping a grayscale image:</a></span></li><li><span><a href="#How-to-reshape-a-color-image?" data-toc-modified-id="How-to-reshape-a-color-image?-3.8"><span class="toc-item-num">3.8&nbsp;&nbsp;</span>How to reshape a color image?</a></span></li><li><span><a href="#Code-of-reshaping-a-color-image:" data-toc-modified-id="Code-of-reshaping-a-color-image:-3.9"><span class="toc-item-num">3.9&nbsp;&nbsp;</span>Code of reshaping a color image:</a></span></li><li><span><a href="#Practice-exercises-for-advanced-operations:" data-toc-modified-id="Practice-exercises-for-advanced-operations:-3.10"><span class="toc-item-num">3.10&nbsp;&nbsp;</span>Practice exercises for advanced operations:</a></span></li></ul></li></ul></div>

# Constants and variables

## `[note-1]` What is [TensorFlow](https://www.tensorflow.org/api_docs/python/tf)?

* Open-source library for graph-based numerical computation:

    * developed by the [Google Brain Team](https://research.google/teams/brain)

* Low-level and high-level APIs:

    * addition, multiplication, differentiation
    
    * machine-learning models

* [Important changes in TensorFlow 2.0](https://www.tensorflow.org/guide/effective_tf2):

    * [eager execution](https://www.tensorflow.org/guide/eager) by default
    
    * model building with [Keras](https://www.tensorflow.org/api_docs/python/tf/keras) and [Estimators](https://www.tensorflow.org/api_docs/python/tf/estimator)

## `[note-2]` What is a tensor?

* Generalization of vectors and matrices.

* Collection of numbers.

* Specific shape.

![What is a tensor](../Figures/1.%20What%20is%20a%20tensor.jpg)

## `[code-1]` Defining tensors in TensorFlow

In [1]:
import tensorflow as tf

# 0D Tensor
d0 = tf.ones((1, ))

d0

<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>

In [2]:
# 1D Tensor
d1 = tf.ones((2, ))

d1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>

In [3]:
# 2D Tensor
d2 = tf.ones((2, 2))

d2

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>

In [4]:
# 3D Tensor
d3 = tf.ones((2, 2, 2))

d3

<tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>

In [5]:
# Print the 3D tensor
print(d3.numpy())

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


## `[note-3]` Defining constants in TensorFlow

* A constant is the simplest category of tensor:

    * not trainable
    
    * can have any dimension

## `[code-2]` Defining constants in TensorFlow

In [7]:
from tensorflow import constant

# Define a 2x3 constant.
a = constant(3, shape=[2, 3])

a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3]], dtype=int32)>

In [8]:
# Define a 2x2 constant.
b = constant([1, 2, 3, 4], shape=[2, 2])

b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

## `[note-4]` Using convenience functions to define constants

![Using convenience functions to define constants](../Figures/2.%20Using%20convenience%20functions%20to%20define%20constants.jpg)

## `[code-3]` Defining and initializing variables

In [17]:
import tensorflow as tf

# Define a variable
a0 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.float32)
a1 = tf.Variable([1, 2, 3, 4, 5, 6], dtype=tf.int16)

a0, a1

(<tf.Variable 'Variable:0' shape=(6,) dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>,
 <tf.Variable 'Variable:0' shape=(6,) dtype=int16, numpy=array([1, 2, 3, 4, 5, 6], dtype=int16)>)

In [18]:
# Define a constant
b = tf.constant(2, tf.float32)

b

<tf.Tensor: shape=(), dtype=float32, numpy=2.0>

In [19]:
# Compute their product
c0 = tf.multiply(a0, b)
c1 = a0 * b

c0, c1

(<tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 2.,  4.,  6.,  8., 10., 12.], dtype=float32)>,
 <tf.Tensor: shape=(6,), dtype=float32, numpy=array([ 2.,  4.,  6.,  8., 10., 12.], dtype=float32)>)

## `[task-1]` Defining data as constants

$\blacktriangleright$ **Package pre-loading**

In [21]:
import pandas as pd
import numpy as np

$\blacktriangleright$ **Data pre-loading**

In [28]:
df = pd.read_csv('../Datasets/1. UCI - default of credit card clients.csv',
                 dtype=np.float64)
credit_numpy = df[['EDUCATION', 'MARRIAGE', 'AGE', 'BILL_AMT1']].to_numpy()

$\blacktriangleright$ **Data exploration**

In [29]:
df[['EDUCATION', 'MARRIAGE', 'AGE', 'BILL_AMT1']].astype(int).head(6)

EDUCATION  MARRIAGE  AGE  BILL_AMT1
0          2         1   24       3913
1          2         2   26       2682
2          2         2   34      29239
3          2         1   37      46990
4          2         1   57       8617
5          1         2   37      64400

$\blacktriangleright$ **Task practice**

In [30]:
# Import constant from TensorFlow
from tensorflow import constant

# Convert the credit_numpy array into a tensorflow constant
credit_constant = constant(credit_numpy)

# Print constant datatype
print('The datatype is:', credit_constant.dtype)

# Print constant shape
print('The shape is:', credit_constant.shape)

The datatype is: <dtype: 'float64'>
The shape is: (30000, 4)


## `[task-2]` Defining variables

$\blacktriangleright$ **Task practice**

In [31]:
import tensorflow as tf
# Define the 1-dimensional variable A1
A1 = tf.Variable([1, 2, 3, 4])

# Print the variable A1
print(A1)

# Convert A1 to a numpy array and assign it to B1
B1 = A1.numpy()

# Print B1
print(B1)

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4], dtype=int32)>
[1 2 3 4]


# Basic operations

## `[note-1]` What is a TensorFlow operation?

![What is a TensorFlow operation](../Figures/3.%20What%20is%20a%20TensorFlow%20operation.jpg)

## `[code-1]` Applying the addition operator

In [32]:
#Import constant and add from tensorflow
from tensorflow import constant, add

# Define 0-dimensional tensors
A0 = constant([1])
B0 = constant([2])

A0, B0

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>,
 <tf.Tensor: shape=(1,), dtype=int32, numpy=array([2], dtype=int32)>)

In [33]:
# Define 1-dimensional tensors
A1 = constant([1, 2])
B1 = constant([3, 4])

A1, B1

(<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>)

In [34]:
# Define 2-dimensional tensors
A2 = constant([[1, 2], [3, 4]])
B2 = constant([[5, 6], [7, 8]])

A2, B2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[5, 6],
        [7, 8]], dtype=int32)>)

In [35]:
# Perform tensor addition with add()
C0 = add(A0, B0)
C1 = add(A1, B1)
C2 = add(A2, B2)

C0, C1, C2

(<tf.Tensor: shape=(1,), dtype=int32, numpy=array([3], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([4, 6], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 6,  8],
        [10, 12]], dtype=int32)>)

## `[note-2]` Performing tensor addition

* The `add()` operation performs **element-wise addition** with two tensors.

* Element-wise addition requires both tensors to have the same shape:

    * scalar addition: $1 + 2 = 3$
    
    * vector addition: $[1, 2] + [3, 4] = [4, 6]$
    
    * matrix addition: $\begin{bmatrix}1 & 2\\ 3 & 4\end{bmatrix}$ + $\begin{bmatrix}5 & 6\\ 7 & 8\end{bmatrix}$ = $\begin{bmatrix}6 & 8\\ 10 & 12\end{bmatrix}$

* The `add()` operator is overloaded.

## `[note-3]` How to perform multiplication in TensorFlow

* **Element-wise multiplication** performed using `multiply()` operation:

    * the tensors multiplied must have the same shape
    
    * e.g., $[1, 2, 3]$ and $[3, 4, 5]$ or $[1, 2]$ and $[3, 4]$

* **Matrix multiplication** performed with `matmul()` operator:

    * the `matmul(A, B)` operation multiplies A by B
    
    * number of columns of A must equal the number of rows of B

## `[code-2]` Applying the multiplication operators

In [38]:
# Import operators from tensorflow
from tensorflow import ones, matmul, multiply

# Define tensors
A0 = ones(1)
A31 = ones([3, 1])
A34 = ones([3, 4])
A43 = ones([4, 3])

A0, A31, A34, A43

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 <tf.Tensor: shape=(3, 1), dtype=float32, numpy=
 array([[1.],
        [1.],
        [1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>)

In [40]:
A0_A0 = multiply(A0, A0)
A31_A31 = multiply(A31, A31)
A34_A34 = multiply(A34, A34)
A43_A43 = multiply(A43, A43)

A0_A0, A31_A31, A34_A34, A43_A43

(<tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 <tf.Tensor: shape=(3, 1), dtype=float32, numpy=
 array([[1.],
        [1.],
        [1.]], dtype=float32)>,
 <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 3), dtype=float32, numpy=
 array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=float32)>)

In [41]:
A34_A43 = matmul(A34, A43)
A43_A34 = matmul(A43, A34)

A34_A43, A43_A34

(<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
 array([[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]], dtype=float32)>,
 <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]], dtype=float32)>)

## `[note-4]` Summing over tensor dimensions

* The `reduce_sum()` operator sums over the dimensions of a tensor:

    * `tensorreduce_sum(A)` sums over all the dimensions of A

    * `reduce_sum(A, i)` sums over the dimension i

## `[code-3]` Summing over tensor dimensions

In [42]:
# Import operations from tensorflow
from tensorflow import ones, reduce_sum

# Define a 2x3x4 tensor of ones
A = ones([2, 3, 4])

A

<tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float32)>

In [44]:
# Sum over all dimensions
B = reduce_sum(A)

B

<tf.Tensor: shape=(), dtype=float32, numpy=24.0>

In [45]:
# Sum over dimensions 0, 1, and 2
B0 = reduce_sum(A, 0)
B1 = reduce_sum(A, 1)
B2 = reduce_sum(A, 2)

B0, B1, B2

(<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
 array([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
 array([[3., 3., 3., 3.],
        [3., 3., 3., 3.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[4., 4., 4.],
        [4., 4., 4.]], dtype=float32)>)

## `[task-1]` Performing element-wise multiplication

$\blacktriangleright$ **Package pre-loading**

In [47]:
from tensorflow import constant, ones_like, multiply

$\blacktriangleright$ **Task practice**

In [48]:
# Define tensors A1 and A23 as constants
A1 = constant([1, 2, 3, 4])
A23 = constant([[1, 2, 3], [1, 6, 4]])

# Define B1 and B23 to have the correct shape
B1 = ones_like([1, 2, 3, 4])
B23 = ones_like([[1, 2, 3], [1, 6, 4]])

# Perform element-wise multiplication
C1 = multiply(A1, B1)
C23 = multiply(A23, B23)

# Print the tensors C1 and C23
print('C1: {}'.format(C1.numpy()))
print('C23: {}'.format(C23.numpy()))

C1: [1 2 3 4]
C23: [[1 2 3]
 [1 6 4]]


## `[task-2]` Making predictions with matrix multiplication

$\blacktriangleright$ **Package pre-loading**

In [27]:
from tensorflow import matmul

$\blacktriangleright$ **Task practice**

In [49]:
# Define features, params, and bill as constants
features = constant([[2, 24], [2, 26], [2, 57], [1, 37]])
params = constant([[1000], [150]])
bill = constant([[3913], [2682], [8617], [64400]])

# Compute billpred using features and params
billpred = matmul(features, params)

# Compute and print the error
error = bill - billpred
print(error.numpy())

[[-1687]
 [-3218]
 [-1933]
 [57850]]


## Practice question for summing over tensor dimensions:

* There is a matrix, `wealth`. This contains the value of the bond and stock wealth for five individuals in thousands of dollars.

* `wealth` $= \begin{bmatrix}11 & 50\\ 7 & 2\\ 4 & 60\\ 3 & 0\\ 25 & 10\end{bmatrix}$

* The first column corresponds to bonds, and the second corresponds to stocks. Each row gives the bond and stock wealth for a single individual. Use `wealth`, `reduce_sum()`, and `.numpy()` to determine which statements are correct about `wealth`.

    $\Box$ The individual in the first row has the highest total wealth (i.e., stocks + bonds).

    $\Box$ Combined, the $5$ individuals hold $\$ 50,000$ in stocks.

    $\boxtimes$ Combined, the $5$ individuals hold $\$ 50,000$ in bonds.

    $\Box$ The individual in the second row has the lowest total wealth (i.e., stocks + bonds).

$\blacktriangleright$ **Package pre-loading**

In [29]:
from tensorflow import constant, reduce_sum

$\blacktriangleright$ **Data pre-loading**

In [30]:
wealth = constant([[11, 50], [7, 2], [4, 60], [3, 0], [25, 10]])

$\blacktriangleright$ **Quiz solution**

In [31]:
wealth

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[11, 50],
       [ 7,  2],
       [ 4, 60],
       [ 3,  0],
       [25, 10]], dtype=int32)>

In [32]:
wealth.numpy()

array([[11, 50],
       [ 7,  2],
       [ 4, 60],
       [ 3,  0],
       [25, 10]], dtype=int32)

In [33]:
reduce_sum(wealth)

<tf.Tensor: shape=(), dtype=int32, numpy=172>

In [34]:
reduce_sum(wealth, 0)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 50, 122], dtype=int32)>

In [35]:
reduce_sum(wealth, 1)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([61,  9, 64,  3, 35], dtype=int32)>

# Advanced operations

## What are the advanced operations?

![Overview of advanced operations](ref5.%20Overview%20of%20advanced%20operations.jpg)

## How to find the optimum?

* In many problems, it is in need to find the optimum of a function:

    * **Minimum**: the lowest value of a loss function

    * **Maximum**: the highest value of the objective function

* It is possible to do this by using the `gradient()` operation:

    * **Optimum**: find a point where $gradient = 0$

    * **Minimum**: change in $gradient > 0$
    
    * **Maximum**: change in $gradient < 0$

## How to calculate the gradient?

![Calculating the gradient](ref6.%20Calculating%20the%20gradient.jpg)

## Code of gradients in TensorFlow:

In [36]:
# Import tensorflow under the alias tf
import tensorflow as tf

# Define x
x = tf.Variable(-1.0)

x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-1.0>

In [37]:
# Define y within instance of GradientTape
with tf.GradientTape() as tape:
    tape.watch(x)
    y = tf.multiply(x, x)

y

<tf.Tensor: shape=(), dtype=float32, numpy=1.0>

In [38]:
# Evaluate the gradient of y at x = -1
g = tape.gradient(y, x)
print(g.numpy())

-2.0


## How to deal with images as tensors?

![Images as tensors](ref7.%20Images%20as%20tensors.jpg)

## How to reshape a grayscale image?

![How to reshape a grayscale image](ref8.%20How%20to%20reshape%20a%20grayscale%20image.jpg)

## Code of reshaping a grayscale image:

In [39]:
# Import tensorflow as alias tf
import tensorflow as tf

# Generate grayscale image
gray = tf.random.uniform([2, 2], maxval=255, dtype='int32')

gray

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  10],
       [232, 243]], dtype=int32)>

In [40]:
# Reshape grayscale image
gray = tf.reshape(gray, [2 * 2, 1])

gray

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[ 89],
       [ 10],
       [232],
       [243]], dtype=int32)>

## How to reshape a color image?

![How to reshape a color image](ref9.%20How%20to%20reshape%20a%20color%20image.jpg)

## Code of reshaping a color image:

In [41]:
# Import tensorflow as alias tf
import tensorflow as tf

# Generate color image
color = tf.random.uniform([2, 2, 3], maxval=255, dtype='int32')

color

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 38,  26,  24],
        [133, 252,  83]],

       [[206, 156,  82],
        [173, 115,  93]]], dtype=int32)>

In [42]:
# Reshape color image
color = tf.reshape(color, [2 * 2, 3])

color

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[ 38,  26,  24],
       [133, 252,  83],
       [206, 156,  82],
       [173, 115,  93]], dtype=int32)>

## Practice exercises for advanced operations:

$\blacktriangleright$ **Task diagram**

![Sign language letter A](ref10.%20Sign%20language%20letter%20A.jpg)

$\blacktriangleright$ **Package pre-loading**

In [43]:
import numpy as np
from tensorflow import reshape

$\blacktriangleright$ **Data pre-loading**

In [44]:
gray_tensor = np.loadtxt("ref11. Gray tensor.csv", delimiter=',')

color_tensor = np.loadtxt("ref12. Color tensor.csv", delimiter=',')
color_tensor = color_tensor.reshape(color_tensor.shape[0],
                                    color_tensor.shape[1] // 3, 3)

$\blacktriangleright$ **Tensor reshaping practice**

In [45]:
# Reshape the grayscale image tensor into a vector
gray_vector = reshape(gray_tensor, (-1, 1))

# Reshape the color image tensor into a vector
color_vector = reshape(color_tensor, (-1, 1))

$\blacktriangleright$ **Task diagram**

![Gradient plot](ref13.%20Gradient%20plot.png)

$\blacktriangleright$ **Package pre-loading**

In [46]:
from tensorflow import Variable, GradientTape, multiply

$\blacktriangleright$ **Gradients optimization practice**

In [47]:
def compute_gradient(x0):
    # Define x as a variable with an initial value of x0
    x = Variable(x0)
    with GradientTape() as tape:
        tape.watch(x)
        # Define y using the multiply operation
        y = multiply(x, x)
    # Return the gradient of y with respect to x
    return tape.gradient(y, x).numpy()


# Compute and print gradients at x = -1, 1, and 0
print(compute_gradient(-1.0))
print(compute_gradient(1.0))
print(compute_gradient(0.0))

-2.0
2.0
0.0


$\blacktriangleright$ **Package pre-loading**

In [48]:
from tensorflow import matmul, reduce_sum

$\blacktriangleright$ **Data pre-loading**

In [49]:
letter = np.array([[1., 0., 1.], [1., 1., 0.], [1., 0., 1.]])

model = np.array([[1., 0., -1.]])

$\blacktriangleright$ **Image data working practice**

In [50]:
# Reshape model from a 1x3 to a 3x1 tensor
model = reshape(model, (3, 1))

# Multiply letter by model
output = matmul(letter, model)

# Sum over output and print prediction using the numpy method
prediction = reduce_sum(output)
print(prediction.numpy())

1.0
